lineログインの実装
yudai64/lookfor pull request #40
Opened 2019-09-15 23:03 UTC by yudai64

2019-09-24 13:33 UTC, toyokappa requested changes
コメントしました。確認お願いします。

2019-09-24 13:33 UTC, toyokappa commented on Gemfile
> +
今更だけど、gemの間に都度改行入れないほうがいいかな。

2019-09-24 13:33 UTC, toyokappa commented on app/models/user.rb
> +    user = User.where(uid: auth.uid, provider: auth.provider).first
deviseのwikiではここでcreate処理してたと思ったけど、そうしなかった理由はなにかある？

2019-09-24 13:33 UTC, toyokappa commented on app/models/user.rb
> +      user = @user = User.new(
なにゆえ`user = @user =`という記載をしているんだろう？

2019-09-24 13:33 UTC, toyokappa commented on app/views/users/sessions/new.html.slim
>        = f.check_box :remember_me
LINEログインのみにするのかと思っていたけど、通常フローも残すの？

2019-09-24 13:37 UTC, yudai64 commented on app/views/users/sessions/new.html.slim
>        = f.check_box :remember_me
LINEログイン完成後に消すつもりです。

2019-09-24 13:39 UTC, yudai64 commented on app/models/user.rb
> +      user = @user = User.new(
全く意味ないです。修正します。

2019-09-24 13:43 UTC, yudai64 commented on app/models/user.rb
> +    user = User.where(uid: auth.uid, provider: auth.provider).first
createにすると `@user.persisted?` が必ずtrueになってしまうのでnewにして、特定出来なかった際(falseの処理)にsaveした方がいいのかと思ってしました。

2019-09-24 13:46 UTC, yudai64 commented on app/models/user.rb
> +    user = User.where(uid: auth.uid, provider: auth.provider).first
ですがtrueとfalseの処理がほぼ一緒でこれでいいのかなという気がしてます。

2019-09-24 14:05 UTC, toyokappa reviewed
コメントしました。

2019-09-24 14:05 UTC, toyokappa commented on app/models/user.rb
> +    user = User.where(uid: auth.uid, provider: auth.provider).first
ごめん、いまいち理由がわからなかった。必ずtrueになると何がまずいんだっけ？

2019-09-24 14:05 UTC, toyokappa commented on app/views/users/sessions/new.html.slim
>        = f.check_box :remember_me
了解。

2019-09-24 14:15 UTC, yudai64 commented on app/models/user.rb
> +    user = User.where(uid: auth.uid, provider: auth.provider).first
`@user.persisted?` でユーザーの特定をしていて、特定出来た時(true)と出来なかった時(false)に処理を分けていると思うのですが、全部が同じ処理になっちゃうのってまずくないですか？

2019-09-25 01:57 UTC, toyokappa commented on app/models/user.rb
> +    user = User.where(uid: auth.uid, provider: auth.provider).first
まずいかどうかは使用によるかなぁと思っていて、どういう仕様を実現しようと思っているか整理しようか。

2019-09-25 06:07 UTC, yudai64 commented on app/models/user.rb
> +    user = User.where(uid: auth.uid, provider: auth.provider).first
`@user = User.from_omniauth(request.env["omniauth.auth"])` 
でomniauthから必要な情報を取り出して@userを検索する。見つからなかったら,omiouthの情報から新たに@userを作成する。

`@user.persisted?` 
で@userがデータベースに存在しているデータか判断

あった場合は@userでログイン
ない場合は@userを保存して、そのデータでログイン

という仕様にしようと思っています。

2019-09-25 06:13 UTC, toyokappa commented on app/models/user.rb
> +    user = User.where(uid: auth.uid, provider: auth.provider).first
システムベースでの仕様を言われてもわからないので、ユーザー視点での仕様を書いてみてもらっても良い？システムベースで書かれた内容を見ると、deviseのwikiの実装でいいじゃんってなりそう。（というか自分の中でも仕様を落としきれてなさそう）

```
# 例
- アカウント登録をしていない場合
  - 登録処理を行い、ログインする
  - ログイン後「新規登録した」という旨のメッセージを表示する
- すでにアカウントを登録している場合
  - そのままログインする
  - ログイン後「ログインした」という旨のメッセージを表示する
```

2019-09-25 06:51 UTC, yudai64 commented on app/models/user.rb
> +    user = User.where(uid: auth.uid, provider: auth.provider).first
ユーザー視点の仕様は書いてくださった通りです。

wikiの実装でやるとアカウントを登録していない場合でも、`@user.persisted?` がtrueになってしまうので変えようと思って変えました。

2019-09-25 07:05 UTC, toyokappa commented on app/models/user.rb
> +    user = User.where(uid: auth.uid, provider: auth.provider).first
その辺りはうまく伝えられるように意識しよう。そんでもって、そのとおりに実装するにあたって、このメソッドは`find_or_inialized_by`というメソッドを使ったほうがスッキリ書けるので、それで書き直してみてください。

また、Controller側で新規作成した旨のメッセージが現状ないと思うのでそちらを追加しよう。また、validationチェックを行わないのであれば`save!`にしておいたほうが良いです。

2019-09-25 07:25 UTC, yudai64 commented on app/models/user.rb
> +    user = User.where(uid: auth.uid, provider: auth.provider).first
伝え方、気をつけてみます。
わかりました。バイトなので帰り次第、実装します。

2019-09-26 09:20 UTC, toyokappa commented on app/models/user.rb
> +      user.name = auth.info.name
いいね:+1:

2019-09-26 09:21 UTC, toyokappa reviewed
ここまではOKそうなので続きよろしく！

2022-12-31 04:00 UTC, closed without merging